#!/usr/bin/env python3
import os
from http.server import BaseHTTPRequestHandler, HTTPServer

HOST = os.environ.get("HOMEPAGE_HOST", "0.0.0.0")
PORT = int(os.environ.get("HOMEPAGE_PORT", "4399"))

URLS = {
    "Shopping": os.environ.get("SHOPPING", "http://127.0.0.1:7770"),
    "Shopping Admin": os.environ.get("SHOPPING_ADMIN", "http://127.0.0.1:7780/admin"),
    "Reddit": os.environ.get("REDDIT", "http://127.0.0.1:9999"),
    "GitLab": os.environ.get("GITLAB", "http://127.0.0.1:8023"),
    "Map": os.environ.get("MAP", "http://127.0.0.1:3000"),
    "Wikipedia": os.environ.get(
        "WIKIPEDIA",
        "http://127.0.0.1:8888/wikipedia_en_all_maxi_2022-05/A/User:The_other_Kiwix_guy/Landing",
    ),
}


def render_page():
    items = "\n".join(
        f'<li><a href="{url}" target="_blank" rel="noopener">{name}</a></li>'
        for name, url in URLS.items()
    )
    return f"""<!doctype html>
<html>
<head>
  <meta charset=\"utf-8\" />
  <title>WebArena Homepage (Local)</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 24px; }}
    h1 {{ margin-bottom: 0.5rem; }}
    ul {{ line-height: 1.8; }}
    .note {{ color: #666; font-size: 0.9rem; }}
  </style>
</head>
<body>
  <h1>WebArena Homepage (Local)</h1>
  <p class=\"note\">Generated by webrarena_homepage_server.py</p>
  <ul>
    {items}
  </ul>
</body>
</html>"""


class Handler(BaseHTTPRequestHandler):
    def do_GET(self):
        page = render_page().encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.send_header("Content-Length", str(len(page)))
        self.end_headers()
        self.wfile.write(page)

    def log_message(self, format, *args):
        return


if __name__ == "__main__":
    httpd = HTTPServer((HOST, PORT), Handler)
    print(f"[homepage] serving on http://{HOST}:{PORT}")
    httpd.serve_forever()
